### ISSUE TITLE
The (somewhat urgent) push to v2.0.0

### ISSUE THREAD

**Issue by phildotdev** [PJL101/iampjl.co.uk#13]
Now that the basics are done, can get a bit jazzier now.
- [ ] #12 - add a blog
- [ ] #9 - switch to fedkit-hugo
- [ ] #8 - online contact form
- [ ] #14 - add reference to the life list
- [ ] Introduction post
- [ ] First content post

I am still torn about #11 so it might not make it for this milestone.

Priority is ASAP for this.
